Trapezoid Generator Function
thedropbears/pydeepspace pull request #13
Opened 2019-02-03 01:18 UTC by Skandis

2019-02-03 01:41 UTC, auscompgeek requested changes

2019-02-03 01:41 UTC, auscompgeek commented on utilities/pure_pursuit.py
> +        self.max_speed = 3  # <-- change to actuall max speed when avaliable
Don't hardcode this. Make this an input.

2019-02-03 01:41 UTC, auscompgeek commented on utilities/pure_pursuit.py
>      def build_path(self, waypoints):
You cannot have code before a docstring. That makes it no longer a docstring.

2019-02-03 01:41 UTC, auscompgeek commented on utilities/pure_pursuit.py
>          Take in a list of waypoints used to build a path.
Why have you removed this line?

2019-02-03 01:41 UTC, auscompgeek commented on utilities/pure_pursuit.py
> +                accel, decel, speed = self.generate_trapezoidal_function(
I don't think you should be hardcoding this either.

2019-02-03 01:41 UTC, auscompgeek commented on utilities/pure_pursuit.py
> +            cos_y = math.cos(angle)
Don't compare to a bool.

2019-02-03 01:41 UTC, auscompgeek commented on utilities/pure_pursuit.py
> +                print(waypoints)
Don't compare to a bool.

If `self.trapezoid` is always a bool, make this an else.

2019-02-03 01:41 UTC, auscompgeek commented on utilities/pure_pursuit.py
>          return vx, vy, heading
Does this actually generate a function?

2019-02-03 06:28 UTC, auscompgeek commented on utilities/pure_pursuit.py
> +        """Generate how far you have to travle to acceleration and deceleration for speed control.
speeel and grandma check

2019-02-04 01:53 UTC, james-ward commented
Have a look at my fork on the trapezoid branch:
https://github.com/james-ward/pydeepspace/tree/trapezoid

The tests are broken, but I think this is a nicer way to do it.

2019-02-09 03:19 UTC, closed without merging